name: First DevOps Workflow

on:
  push:
    branches: [ main ]

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello from GitHub Actions!"